version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EcommerceBackend
    depends_on:
      - db
    ports:
      - '5454:5454'
  db:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: