server:
  port: 5454

spring:

#  config:
#    import: optional:file:.env[.properties]
  datasource:
#    url: jdbc:mysql://localhost:3306/ecommerceback
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 587595
    url: jdbc:mysql://root:ZTanSQQDDWEfTSaJcxXMAlnQHtZVSjpD@monorail.proxy.rlwy.net:21556/railway
#  jpa:
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true

RAZORPAY_PUBLISHABLE_ID: "rzp_test_Q0QTYcgPygZd5V"
RAZORPAY_SECRET_KEY: "DCwc8GO9rqJBEPr7SJaiPXxb"