server:
  port: 5454

spring:
#  config:
#    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:ecommerce}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MYSQLPASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

RAZORPAY_PUBLISHABLE_ID: "rzp_test_Q0QTYcgPygZd5V"
RAZORPAY_SECRET_KEY: "DCwc8GO9rqJBEPr7SJaiPXxb"