server:
  port: 5454

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?currentSchema=${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

RAZORPAY_PUBLISHABLE_ID: "rzp_test_Q0QTYcgPygZd5V"
RAZORPAY_SECRET_KEY: "DCwc8GO9rqJBEPr7SJaiPXxb"